### ISSUE TITLE
Problema en calendario

### ISSUE THREAD

**Issue by monster3dani** [julienV/Joomla-Tracks#69]
Hola acabo de darme cuenta de un detalle, en el calendario...
Adjunto imagen.
![image](https://user-images.githubusercontent.com/64259984/80748270-f264d780-8b24-11ea-992e-23c3dd0f9880.png)
Si te fijas, no he insertado los datos de esas 3 ultimas carreras, pero veo en la columna de equipos que sale reflejado un equipo por carrera, no tendria que haber nada.

**Comment by monster3dani** [comment]
Tambien quiero comentar que en este mismo apartado puedo ver 2 ganadores en la carrera de Silverstone, pero en las demas carreras solo sale 1 ganador, hacemos un campeonato semanal donde hay 2 carreras diarias...

**Comment by julienV** [comment]
Hi Dani,
I have found the issue for wrong team winner.
but for individual winner, it's normal: what is displayed here, is the 'global' winner for the round, not the winners of each round 'events'. So, i am guessing that you see 2 winners in the first stage because it is a tie between those 2 (same number of points...)

**Comment by monster3dani** [comment]
Ok thks i understand
